on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: check ssh folder
      run: |
        echo "Listing ~/.ssh folder contents:"
        ls -la ~/.ssh
        echo "Checking id_rsa permissions:"
        stat ~/.ssh/id_rsa
        echo "Checking known_hosts permissions:"
        stat ~/.ssh/known_hosts

    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "cd ${{ secrets.WORK_DIR }} && git pull"

    - name: cleanup
      run: rm -rf ~/.ssh
