name: Remote SSH Command
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ${{secrets.WORK_DIR}}
            # Configuration Git
            git config --global credential.helper store
            git config --global user.name "Jean-Lionel"
            git config --global user.email "nijeanlionel@gmail.com"
            git config pull.rebase true

            # Mettre à jour la branche distante avec rebase en utilisant le token GitHub
            git reset --hard HEAD
            git clean -f -d
            git checkout ${{secrets.MAIN_BRANCH}}
            git pull https://${{ secrets.GIT_TOKEN }}@github.com/Advanced-IT-Research-Burundi/advanced_boutique_ui.git ${{secrets.MAIN_BRANCH}}

            # Confirmation du déploiement
            echo "Deployed successfully" >> deploy.log
            date +"%Y-%m-%d %H:%M:%S" >> deploy.log
            # Installer les dépendances et builder le projet
            npm install
            npm run build
